FROM python:3.14-slim

WORKDIR /app

# Copy everything that is necessary
COPY requirements.txt .
COPY common/ ./common/
COPY config/ ./config/
COPY producer/ ./producer/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Sets the working directory for the producer
WORKDIR /app/producer

# Command to run
CMD ["python", "main.py"]